### ISSUE TITLE
Location Groupings

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#1]
1. by admin1
2. by admin2
3. custom

**Comment by drfaustusfade** [comment]
![chrome_5yKnw6y3L6](https://user-images.githubusercontent.com/29349472/91692382-894aaa80-eb7e-11ea-9139-0d3c0cd0962b.png)
![chrome_xMHSfdEIEE](https://user-images.githubusercontent.com/29349472/91692417-9a93b700-eb7e-11ea-8bce-14942bf57853.png)
![chrome_2CLic1Tw7e](https://user-images.githubusercontent.com/29349472/91692421-9cf61100-eb7e-11ea-8af9-cb3a4177e4d2.png)

**Comment by drfaustusfade** [comment]
rolled out, testing

**Comment by drfaustusfade** [comment]
there is a bug when adding a new project, and grouping locations (by district) before adding ones, the location groups will not be assigned to locations

**Comment by drfaustusfade** [comment]
please also add admin1 name on district card

**Comment by drfaustusfade** [comment]
adding a location on group persist to another location group if not saved, if a user is not saving location on navigation out, the location should not be persisted

**Comment by fakhrihawari** [comment]
> there is a bug when adding a new project, and grouping locations (by district) before adding ones, the location groups will not be assigned to locations

Link PR for bugfix
https://github.com/drfaustusfade/ngm-reportHub/pull/35
