### ISSUE TITLE
Overlapping input labels

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#15]
![chrome_FiGNqqTh8v](https://user-images.githubusercontent.com/29349472/102180969-6347dc80-3ec7-11eb-965e-da5ca3d6726e.png)
Pic 1 Overlapping lable after hrp switch off/on

- [x] to check for overlapping labels

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/39
