### ISSUE TITLE
user minor registration and logout bugs

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#17]
- [x] to fix when on registration inputs after visiting public dashboard contain public user values
- [x] to fix when on registration selecting immap throws console error onOrganizationSelected adminRpcode (Cannot read property 'toLowerCase' of undefined)
- [x] to fix when logging out from team page throws console error on disabledOrgcheckCloseRegisteration (Cannot read property 'roles' of undefined)

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/39
