### ISSUE TITLE
consider to drop angular material

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#18]
would it be possible to drop angular material, and use just materialize, as right now former is quite heavy to bundle, and not much out of it is used
https://bundlephobia.com/scan-results?packages=angular@1.4.8,angular-animate@1.4.8,angular-aria@1.4.8,angular-cookies@1.4.8,angular-filter-count-to@0.0.3,angular-leaflet-directive@0.8.8,angular-material@1.1.18,angular-resource@1.4.8,angular-route@1.4.8,angular-sanitize@1.4.8,angular-simple-logger@0.0.4,angular-touch@1.4.8,angular-translate@2.18.1,angular-utils-pagination@0.11.0,angular-xeditable@0.6.0,cal-heatmap@3.5.3,d3@3.5.6,highcharts@4.1.9,highcharts-ng@0.0.11,jquery@2.2.0,jquery-animate-scroll@1.0.0,leaflet@0.7.5,leaflet-control-geocoder@1.3.4,leaflet-fullscreen@1.0.2,leaflet.markercluster@0.4.0,materialize-css@1.0.0,moment@2.10.6,ng-csv@0.3.6,ng-infinite-scroll@1.3.0,ng-table@0.8.3&sortMode=size

**Comment by fakhrihawari** [comment]
branch dropdown angular material
https://github.com/fakhrihawari/ngm-reportHub/tree/drop-angular-material
