### ISSUE TITLE
Update User Guide Links

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#26]
- [x] add Download COVID-19 Guide
- [x] add to cluster/guides User, and COVID-19 options, maybe iframe to show onpage

https://reporthub.org/report/guide/ReportHub_User_Guide.pdf
https://reporthub.org/report/guide/ReportHub_COVID19_Guide.pdf

https://drive.google.com/drive/folders/1MsBLlLkcPz2tdelaYrAe3EfMMnodWZ18?usp=sharing

**Comment by fakhrihawari** [comment]
<img width="973" alt="Screen Shot 2021-01-11 at 16 57 44" src="https://user-images.githubusercontent.com/12655589/104166994-3509de00-542e-11eb-84d8-b007aa551bd6.png">

put it in there (contact)?

**Comment by drfaustusfade** [comment]
there additional _Download COVID-19 Guide_

**Comment by fakhrihawari** [comment]
https://user-images.githubusercontent.com/12655589/104269170-3556b780-54c8-11eb-902c-49de607a0927.mp4

**Comment by fakhrihawari** [comment]
<img width="989" alt="Screen Shot 2021-01-12 at 11 27 05" src="https://user-images.githubusercontent.com/12655589/104269540-202e5880-54c9-11eb-967d-5d7a84fb61b0.png">

**Comment by drfaustusfade** [comment]
perfect, if having the same frame for general guide good to go.

**Comment by fakhrihawari** [comment]
so no need use modal?

**Comment by fakhrihawari** [comment]
<img width="1290" alt="Screen Shot 2021-01-12 at 13 35 02" src="https://user-images.githubusercontent.com/12655589/104278331-0433b280-54db-11eb-9472-39bca18f816a.png">
like this?

**Comment by drfaustusfade** [comment]
also ok, up to you for you think will look better, i mean having also the same for General User Guidance in addition to COVID-19

**Comment by fakhrihawari** [comment]
ok i will make a pull request

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/52

**Comment by drfaustusfade** [comment]
- [x] check that guides and links open in a new window

**Comment by fakhrihawari** [comment]
> * [ ]  check that guides and links open in a new window

all link? so no need to use iframe ?

**Comment by drfaustusfade** [comment]
> > * [ ]   check that guides and links open in a new window
> 
> all link? so no need to use iframe ?

for links that navigate to different pages

**Comment by fakhrihawari** [comment]
Link PR : https://github.com/drfaustusfade/ngm-reportHub/pull/127
