### ISSUE TITLE
UI: Delete Project Button Permissions

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#27]
only for admin users / disallow for a regular user
ORG, CLUSTER, CONTRY_ADMIN, SUPER_ADMIN

**Comment by fakhrihawari** [comment]
<img width="572" alt="Screen Shot 2021-01-12 at 16 25 29" src="https://user-images.githubusercontent.com/12655589/104295276-d22e4a80-54f2-11eb-8afa-edf87a5bb750.png">

just delete button or complete button too?

**Comment by drfaustusfade** [comment]
delete button

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/58

**Comment by drfaustusfade** [comment]
https://github.com/drfaustusfade/ngm-reportHub/pull/58/files
please create and use config on premissions object, to have property if role is admin or not, ADMIN: true/false 
as there is af vs non af, please set it to not show it for af only

**Comment by fakhrihawari** [comment]
So Hide delete button only on AF right?

**Comment by fakhrihawari** [comment]
Updated

**Comment by drfaustusfade** [comment]
I put some comments on review https://github.com/drfaustusfade/ngm-reportHub/pull/58/files

**Comment by fakhrihawari** [comment]
there is no review, where is it?

**Comment by fakhrihawari** [comment]
Okay, Updated
