### ISSUE TITLE
ui: array changes are not detected

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#29]
after update to 1.8 array changes are not detected, that are triggered from interface, wrapping in $timeout solves digest (for example commit ec63dfd974fe752657577678464c0fcb8d741adb)
- [x] to check if array updates are reflected on models on interface changes in such functions

**Comment by fakhrihawari** [comment]
in target beneficiaries and target location OK
In financial report, and stock OK
In monthly report OK
