### ISSUE TITLE
Add Service Desk Form Link

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#30]
- [x] add on login/register page, in footer Contact link (like on other pages)
- [x] on contact modal and feedback page add a section for service desk link https://reporthub.atlassian.net/servicedesk/customer/portal/1 (opens on a new page)
- [x] rename User Guide REPORTHUB to User Guides

**Comment by fakhrihawari** [comment]
1. Login/Register
<img width="837" alt="Screen Shot 2021-01-18 at 09 42 39" src="https://user-images.githubusercontent.com/12655589/104866605-8dcb0080-5971-11eb-8c1f-9d74b1f371b7.png">
<img width="849" alt="Screen Shot 2021-01-18 at 09 42 27" src="https://user-images.githubusercontent.com/12655589/104866609-902d5a80-5971-11eb-8a9b-f69752e8d49b.png">

2.
<img width="1171" alt="Screen Shot 2021-01-18 at 09 38 32" src="https://user-images.githubusercontent.com/12655589/104866689-beab3580-5971-11eb-98e3-b1dc7aaaf802.png">

3.
<img width="1022" alt="Screen Shot 2021-01-18 at 09 38 18" src="https://user-images.githubusercontent.com/12655589/104866703-c7037080-5971-11eb-931e-542f69315cb9.png">

**Comment by fakhrihawari** [comment]
If you okay with that mockup, I will make PR

**Comment by drfaustusfade** [comment]
nice, please put
- Services before User Guides, to name it Support Services
- Purpose: You can request support and get support for any ReportHub question 

additionally, please remove REPORTHUB from Contact REPORTHUB on modal
to rename Contact Per Country to Country Contact

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/66
