### ISSUE TITLE
Dashboards start date

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#32]
follow everyone AF start date calculation, to reduce unnecessary load and select the relevant year

**Comment by fakhrihawari** [comment]
The dashboards always start one first date of that year ;
if the new date is in first month of the new year , do we set the date 1 month before (2020-12-1)?
or keep set to first date of the year(2021-01-01)?

**Comment by drfaustusfade** [comment]
like https://github.com/drfaustusfade/ngm-reportHub/blob/e9f9956318363abcc532d54c62dbae460322cddc/app/scripts/modules/cluster/app.js#L553
applicable to dashboards (5W) having a fixed start date

**Comment by fakhrihawari** [comment]
i mean if the current date now is 2021-01-18 then the startdate is => 2021-01-01 or 2020-10-01?

**Comment by drfaustusfade** [comment]
now => subtract 2 month => start of year 
for example as of today would be 2020-01-01

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/70
