### ISSUE TITLE
Select Issue

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#33]
Sometimes select is not working on selecting an option
resolved after browser reload
- [ ] to investigate what could be the issue

**Comment by fakhrihawari** [comment]
Which place this did issue happen?

**Comment by drfaustusfade** [comment]
so far on stocks unit type selection and registration cluster selection

**Comment by fakhrihawari** [comment]
on the stock unit type, I spotted the bug but  I already put 'watch' directive to solve it .  Do already try it ?

**Comment by drfaustusfade** [comment]
so far no issue after both incidents, there might be some issue with the select directive on asynchronous evaluation in angular 1.8, in any case, better to keep an eye on it in case that happens again

**Comment by drfaustusfade** [comment]
watch-model should be used
