### ISSUE TITLE
Clusters contact list page

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#36]
Requirements
- for all registered users
- to show cluster/wg/sector contacts
- one cluster can have multiple contacts
- usual contact details name, email, phone, position
- admins of corresponding clusters/wg/sector should be able to update
- country admin can update any cluster

**Comment by fakhrihawari** [comment]
what is cluster/wg ??
Can you explain this page purpose?

**Comment by fakhrihawari** [comment]
Mockup
<img width="1303" alt="Screen Shot 2021-01-19 at 10 57 28" src="https://user-images.githubusercontent.com/12655589/104986233-31391580-5a45-11eb-9c05-ca6357ab289b.png">

**Comment by drfaustusfade** [comment]
> Can you explain this page purpose?

Clusters are groups of humanitarian organizations, both UN and non-UN, in each of the main sectors of humanitarian action (water, health, shelter, logistics, etc.). They have clear responsibilities for coordination.
Each cluster has cluster members.

In the case of ReportHub:
Users with Cluster role are cluster accounts (data consumers)
Users with User, Org are cluster member accounts (data producers).

The purpose of the page is to provide to cluster member cluster contacts.

![chrome_5n5V0FoZwn](https://user-images.githubusercontent.com/29349472/104998772-65163a00-5a49-11eb-8acf-1f9d84695f9f.png)

**Comment by fakhrihawari** [comment]
so in the  contac list is user with role CLUSTER right?
and for point 5,6 what kind update is that ?

**Comment by drfaustusfade** [comment]
> so in the contac list is user with role CLUSTER right?
> and for point 5,6 what kind update is that ?

I was thinking more like cluster profiles, cluster themselves update their current contact information, hence that includes 5,6 point,
but maybe a better idea that we can just add for CLUSTER users on profile additional property cluster contact and show it in a table like for the team page

**Comment by fakhrihawari** [comment]
so just like organization profile?
for now, I just put table with user with CLUSTER role in it like in the mockup above

**Comment by drfaustusfade** [comment]
Maybe, I think it is alright like you did plus adding cluster column name, but just adding checkbox on user profile contact and filtering additional attribute to specify if any Cluster or Country Admin user is _Cluster Contact_

**Comment by fakhrihawari** [comment]
make checkbox like this?
<img width="866" alt="Screen Shot 2021-01-19 at 14 39 53" src="https://user-images.githubusercontent.com/12655589/105002654-39ed1400-5a64-11eb-90c8-f7bbf0a747a6.png">

**Comment by drfaustusfade** [comment]
I think checkbox on contact labelled section would be suitable if that will look ok

**Comment by fakhrihawari** [comment]
who will be the one to check and uncheck this checkbox?

**Comment by drfaustusfade** [comment]
users themselves, or on behalf of them other admins with corresponding permissions

**Comment by fakhrihawari** [comment]
<img width="856" alt="Screen Shot 2021-01-19 at 16 13 21" src="https://user-images.githubusercontent.com/12655589/105013172-89860c80-5a71-11eb-8cc9-9c3d6efb3679.png">

so this checkbox only appear on user with role 'CLUSTER' and 'COUNTRY_ADMIN'?

**Comment by drfaustusfade** [comment]
of the same country scope
for users having roles CLUSTER, COUNTRY, COUNTRY_ADMIN
user with CLUSTER role can set/unset to be a cluster contact
user with CLUSTER role of the same cluster can set/unset Cluster Contact (case when cluster admin changed)
user with COUNTRY_ADMIN can set/unset CLUSTER, COUNTRY, COUNTRY_ADMIN users (case when cluster admin changed)

**Comment by fakhrihawari** [comment]
Updated:
https://github.com/fakhrihawari/ngm-reportEngine/tree/pwd-update
https://github.com/fakhrihawari/ngm-reportHub/tree/contact-list-page

if you okay i will make PR

**Comment by drfaustusfade** [comment]
- get only user contacts that are cluster_contacts adding param to filter
- align profile cluster contact checkbox to be evenly distanced from input elements (bigger top margin)
- save profile on update as for other inputs

**Comment by fakhrihawari** [comment]
<img width="1479" alt="Screen Shot 2021-01-20 at 13 38 37" src="https://user-images.githubusercontent.com/12655589/105136797-d4ad2780-5b24-11eb-9b69-5e571476a5bc.png">

Btw do we need to filter country too?

**Comment by drfaustusfade** [comment]
alright, i think checkbox visually looks a bit off as it is left-aligned, anyway

by country yes, that's by default, as database tenancy is by country

**Comment by fakhrihawari** [comment]
<img width="297" alt="Screen Shot 2021-01-20 at 15 55 05" src="https://user-images.githubusercontent.com/12655589/105150931-f1068f80-5b37-11eb-9e71-e8949b340caa.png">

Put it here?

**Comment by drfaustusfade** [comment]
alright,  let's name CLUSTER CONTACTS
let's restructure and put like that in a separate commit, I think there will be a better place
Under CONTACTS menu
   > TECHNICAL CONTACTS
   > CLUSTER CONTACTS
   > ORGANIZATION CONTACTS

**Comment by fakhrihawari** [comment]
> alright, let's name CLUSTER CONTACTS
> let's restructure and put like that in a separate commit, I think there will be a better place
> Under CONTACTS menu
> 
> > TECHNICAL CONTACTS
> > CLUSTER CONTACTS
> > ORGANIZATION CONTACTS

i will make another PR for menu,

and this is for contact list page:
https://github.com/drfaustusfade/ngm-reportHub/pull/73
https://github.com/drfaustusfade/ngm-reportEngine/pull/18

**Comment by drfaustusfade** [comment]
ok, but the country filter is just for roles above country admin, otherwise the default of user's country
remove in subtitle trailing Cluster suffix as for example MPC is a working group, or could be sector
are users filtered by cluster_contact condition?

**Comment by fakhrihawari** [comment]
the users that show in the list is a user with cluster_contact = true,

Updated : country filter only for country admin above

**Comment by drfaustusfade** [comment]
alright, if it is a specialized function please just rename function to something like getClusterContactUsers to understand better the function purpose

**Comment by drfaustusfade** [comment]
not a big deal but, for future refactoring would having an additional filter on query not be better if there is no indexing on cluster_contact? so that not to run electricity to fetch the records

**Comment by fakhrihawari** [comment]
> not a big deal but, for future refactoring would having an additional filter on query not be better if there is no indexing on cluster_contact? so that not to run electricity to fetch the records

Sorry? what do you mean?

**Comment by drfaustusfade** [comment]
i mean why not to put into the filter, but not an issue on that scale

```
User
      .find()
      .where(filterAdmin0pcode)
      .where(filterClusterId)
                                      <== 
      .exec(function (err, user) {

        // return error
        if (err) return res.negotiate(err);
        
        if (user && user.length){
          user = _.filter(user,function(u){
            return u.cluster_contact; <==
          })
        };
        if (r
```

**Comment by fakhrihawari** [comment]
> i mean why not to put into the filter, but not an issue on that scale
> 
> ```
> User
>       .find()
>       .where(filterAdmin0pcode)
>       .where(filterClusterId)
>                                       <== 
>       .exec(function (err, user) {
> 
>         // return error
>         if (err) return res.negotiate(err);
>         
>         if (user && user.length){
>           user = _.filter(user,function(u){
>             return u.cluster_contact; <==
>           })
>         };
>         if (r
> ```

Updated

**Comment by drfaustusfade** [comment]
ok, testing with COUNTRY ADMIN cluster user cannot be set to Cluster Conact on profile as checkbox is disabled

**Comment by fakhrihawari** [comment]
> ok, testing with COUNTRY ADMIN cluster user cannot be set to Cluster Conact on profile as checkbox is disabled
what the role user that u want to set as cluster contact

**Comment by drfaustusfade** [comment]
cluster role

**Comment by fakhrihawari** [comment]
> cluster role
what your role?
hmm it s weird i can set user with my role as country admin, try hard refresh?

**Comment by drfaustusfade** [comment]
ok that's because I have both country and country admin roles and the have the same level, should be updated in a separate commit

**Comment by fakhrihawari** [comment]
> alright, let's name CLUSTER CONTACTS
> let's restructure and put like that in a separate commit, I think there will be a better place
> Under CONTACTS menu
> 
> > TECHNICAL CONTACTS
> > CLUSTER CONTACTS
> > ORGANIZATION CONTACTS

<img width="315" alt="Screen Shot 2021-01-22 at 08 05 18" src="https://user-images.githubusercontent.com/12655589/105431802-f6272400-5c88-11eb-9194-d4b8a5d3c73c.png">


PR For restructure contacts
https://github.com/drfaustusfade/ngm-reportHub/pull/76
