### ISSUE TITLE
Check sentry stock errors

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#37]
There were some sentry errors to investigate
```
arguments: [{"message":"Cannot read property 'stock_item_type' of null","name":"TypeError","stack":"TypeError: Cannot read property 'stock_item_type' of null\n    at Object.rowSaveDisabled

arguments: [{"message":"Cannot read property 'beneficiaries_covered' of null","name":"TypeError","stack":"TypeError: Cannot read property 'beneficiaries_covered' 

```

**Comment by drfaustusfade** [comment]
also, non-essencial error on adding stock for ET 
```
TypeError: Cannot read property '0' of undefined
    at Object.rowSaveDisabled
 if (($data.implementing_partners && !$data.implementing_partners[0] || !$data.implementing_partners[0].organization_tag) || ($data.donors && !$data.donors[0] || !$data.donors[0].donor_id) || detailRowDisabled)
```

**Comment by fakhrihawari** [comment]
> stock_item_type

rowSaveDisabled function only use in old stocks form (stocks.html) but i check in the code,  all country use stocks-reform.html

**Comment by fakhrihawari** [comment]
> There were some sentry errors to investigate
> 
> ```
> arguments: [{"message":"Cannot read property 'stock_item_type' of null","name":"TypeError","stack":"TypeError: Cannot read property 'stock_item_type' of null\n    at Object.rowSaveDisabled
> 
> arguments: [{"message":"Cannot read property 'beneficiaries_covered' of null","name":"TypeError","stack":"TypeError: Cannot read property 'beneficiaries_covered' 
> ```

i try to find the problem but not find the clue

**Comment by fakhrihawari** [comment]
> also, non-essencial error on adding stock for ET
> 
> ```
> TypeError: Cannot read property '0' of undefined
>     at Object.rowSaveDisabled
>  if (($data.implementing_partners && !$data.implementing_partners[0] || !$data.implementing_partners[0].organization_tag) || ($data.donors && !$data.donors[0] || !$data.donors[0].donor_id) || detailRowDisabled)
> ```

For Implementing partner and donor are mandatory for ET?

**Comment by drfaustusfade** [comment]
i as recall they can be skipped, not mandatory inputs

**Comment by fakhrihawari** [comment]
LInk bug fix:
https://github.com/drfaustusfade/ngm-reportHub/pull/74

**Comment by drfaustusfade** [comment]
> i as recall they can be skipped, not mandatory inputs

if selecting donor or implementing partner and then deselecting then it will error as required
maybe also putting regular no option '-' instead of Select...

**Comment by fakhrihawari** [comment]
> > i as recall they can be skipped, not mandatory inputs
> 
> if selecting donor or implementing partner and then deselecting then it will error as required
> maybe also putting regular no option '-' instead of Select...

ok

**Comment by fakhrihawari** [comment]
> > > i as recall they can be skipped, not mandatory inputs
> > 
> > 
> > if selecting donor or implementing partner and then deselecting then it will error as required
> > maybe also putting regular no option '-' instead of Select...
> 
> ok

updated

**Comment by drfaustusfade** [comment]
thank you, i mean if selecting donor or implementing partner and then deselecting then it should not error 
![chrome_Lmw1kyQdRk](https://user-images.githubusercontent.com/29349472/105322228-3386a580-5be6-11eb-9386-e6ab27331750.png)

**Comment by fakhrihawari** [comment]
okay, i will remove donor and implementation partner from validation ;

and updated
