### ISSUE TITLE
beneficiary types by activity

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#39]
right now beneficiary types are by cluster, that is sufficient in most cases 
functionality to have beneficiary types by activity is needed for some cases
possible solutions: 
- array of beneficiary types by activity
- array of beneficiary ids by activity to be filtered
- group id tag to select the corresponding list
...

the first usual option should work just fine, and quite efficient on gzip if many repeated entries

**Comment by fakhrihawari** [comment]
Mock Up:
https://github.com/fakhrihawari/ngm-reportHub/tree/benef-activity-array

Please give note or comment if something not right

**Comment by drfaustusfade** [comment]
quickly checking works fine 
if addint just ng-if="ngmClusterBeneficiaries.form[ 0 ][ $indexRecord ][ 'beneficiary_type_id' ] or not ng-if="!ngmClusterBeneficiaries.form[ 0 ][ $indexRecord ][ 'beneficiary_type_id' ] should be alright
please pull

**Comment by drfaustusfade** [comment]
also backend activities processing on import script https://github.com/drfaustusfade/ngm-reportEngine/pull/22

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/89

**Comment by drfaustusfade** [comment]
thank you
updated DEV and PROD
