### ISSUE TITLE
Feat: Activities Progress New Beneficiaries

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#4]
Activities Progress should be compared to new beneficiaries
- [x] to rename Reported Beneficiaries to Services to Beneficiaries
- [x] to add column New Beneficiaries with new beneficiaries number that is delivery_type_id: 'population' (delivery_type_name: 'New Beneficiaries')
- [x] to use for progress new beneficiaries or to add additional
- [x] to use total_beneficiaries for calculation

**Comment by fakhrihawari** [comment]
Can you explain to me point 3 and 4?

**Comment by drfaustusfade** [comment]
3 for progress calculation to use beneficiaries records where delivery_type_id: 'population' (new beneficiaries), or have two calculations/columns: total beneficiaries / total target (% progress for Services to Beneficiaries) and beneficiaries with delivery population / total target beneficiaries ( % progress for New Beneficiaries )
4 total_beneficiaries  in place of summing boys, girls, men, women, elderly men, elderly women ...

**Comment by fakhrihawari** [comment]
<img width="1255" alt="Screen Shot 2020-12-16 at 13 22 25" src="https://user-images.githubusercontent.com/12655589/102312705-c6a63d00-3fa1-11eb-9583-d0a01b5b9934.png">

**Comment by fakhrihawari** [comment]
Service To Beneficiaries : 16038;
new beneficiaries : 15988;

If the Service To Beneficiaries(total_beneficiaries) and new beneficiaries ( beneficairies with delivery_type = "popullation") is almost have same amount it will look like that

Is it okay?
If you okay, i will make PR

**Comment by drfaustusfade** [comment]
Yes, that’s alright

**Comment by drfaustusfade** [comment]
That also brings to the point as additional feature  to show % of new beneficiaries, as we usually show that number on dashboards, if there will be space for it

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/39
https://github.com/drfaustusfade/ngm-reportEngine/pull/12
