### ISSUE TITLE
Additional Correction of Project to Activity renaming

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#5]
Activity Plan

Project Page
Activities Plan => Activity Plan
BACK TO PROJECT SUMMARY => BACK TO ACTIVITY PLAN SUMMARY
Please complete a Project Plan and enter a summary description including objectives.. => Please complete an Activity Plan

Project Summary Page
Planned Activities => Activity Plan
Mark Activity As Complete => Complete Activity Plan
Delete Activity => Delete Activity Plan

list projects
AFG | Activities => AFG | Activity Plans
add new plan => add new activity plan
All Activities for Afghanistan => All Activity Plans in Afghanistan

organizations page 
Activities => Activity	

5w PROJECT LOCATIONS => ACTIVITY LOCATIONS

Admin in Menu Projects Admin => Progress Admin
Activities Progress => Activity Progress

**Comment by fakhrihawari** [comment]
Link PR
https://github.com/drfaustusfade/ngm-reportHub/pull/39
