### ISSUE TITLE
focal point using select

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#50]
- [x] to try using regular select or another way, that is migrating from exeditable

**Comment by fakhrihawari** [comment]
<img width="1256" alt="Screen Shot 2021-02-08 at 16 46 02" src="https://user-images.githubusercontent.com/12655589/107202824-362e2b00-6a2d-11eb-8e06-9787d6fe330e.png">

**Comment by drfaustusfade** [comment]
then maybe save and cancel button is not needed

**Comment by fakhrihawari** [comment]
https://user-images.githubusercontent.com/12655589/107304122-0590d480-6ab3-11eb-9d39-af0729390191.mp4

keep the edit button or remove it?

**Comment by drfaustusfade** [comment]
i like the look of it, can we not keep it for a _new_ project

and let have text on toast _Please save the project to apply the changes_

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/97
