### ISSUE TITLE
Feat PWD input

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#6]
AF WASH cluster request for 2021
Add additional input for _Persons with Disabilities_ that will specify the total number of PWD from the total beneficiaries with a tooltip: # of people from total
based on activities config total_pwd

**Comment by fakhrihawari** [comment]
Like This ?
<img width="843" alt="Screen Shot 2020-12-16 at 14 29 58" src="https://user-images.githubusercontent.com/12655589/102318022-379e2280-3fab-11eb-92d0-92d6c9d21ad1.png">

**Comment by drfaustusfade** [comment]
could be, also number >=0, <= total

**Comment by fakhrihawari** [comment]
<img width="662" alt="Screen Shot 2020-12-16 at 14 47 08" src="https://user-images.githubusercontent.com/12655589/102319540-a2505d80-3fad-11eb-96d4-9cd33932927e.png">

**Comment by fakhrihawari** [comment]
<img width="899" alt="Screen Shot 2020-12-16 at 14 48 07" src="https://user-images.githubusercontent.com/12655589/102319617-c318b300-3fad-11eb-8dab-cd0e58e903e9.png">

**Comment by drfaustusfade** [comment]
_also number >=0, <= total_ i mean number validation 
labeb # of people from total

**Comment by fakhrihawari** [comment]
<img width="1107" alt="Screen Shot 2020-12-16 at 15 06 30" src="https://user-images.githubusercontent.com/12655589/102321498-52bf6100-3fb0-11eb-888d-b91e80c4eb45.png">

**Comment by fakhrihawari** [comment]
did you already  add config total_pwd in activities config?

**Comment by drfaustusfade** [comment]
alright, not yet, will be added when updating wash activities for the next year

**Comment by drfaustusfade** [comment]
this feature is tentative experimental, as there is already countrywide beneficiary category to that purpose, but it looks like it is ignored mostly, and wash cluster prefers that way

**Comment by fakhrihawari** [comment]
Link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/41

**Comment by drfaustusfade** [comment]
- [x] add an attribute to the beneficiaries model, without default
- [x] on adding new beneficiaries delete the property, with a helper function

**Comment by fakhrihawari** [comment]
Update:
https://github.com/drfaustusfade/ngm-reportHub/pull/68
https://github.com/drfaustusfade/ngm-reportEngine/pull/17/files

**Comment by drfaustusfade** [comment]
thank you

**Comment by drfaustusfade** [comment]
on activity change should also be cleared for example switching between activities having such input and not having

**Comment by fakhrihawari** [comment]
> on activity change should also be cleared for example switching between activities having such input and not having

Link Update:
https://github.com/drfaustusfade/ngm-reportHub/pull/71

**Comment by drfaustusfade** [comment]
sentry error
```
if (!ngmClusterBeneficiaries.form[$locationIndex][$beneficiaryIndex]['total_pwd'] && beneficiary.total_pwd){
					delete beneficiary.total_pwd;
				}

ReferenceError: $locationIndex is not defined undefined
arguments: [{"message":"$locationIndex is not defined","name":"ReferenceError","stack":"ReferenceError: $locationIndex is not defined\n    at Object.setBeneficiaries
```
bugfix: https://github.com/drfaustusfade/ngm-reportHub/pull/75

**Comment by fakhrihawari** [comment]
> sentry error
> 
> ```
> if (!ngmClusterBeneficiaries.form[$locationIndex][$beneficiaryIndex]['total_pwd'] && beneficiary.total_pwd){
> 					delete beneficiary.total_pwd;
> 				}
> 
> ReferenceError: $locationIndex is not defined undefined
> arguments: [{"message":"$locationIndex is not defined","name":"ReferenceError","stack":"ReferenceError: $locationIndex is not defined\n    at Object.setBeneficiaries
> ```
> 
> bugfix: [drfaustusfade/ngm-reportHub#75](https://github.com/drfaustusfade/ngm-reportHub/pull/75)

Thank you :), i forgot to change the index

**Comment by drfaustusfade** [comment]
updated for target beneficiaries also, with default 0 for existing records
