### ISSUE TITLE
reformed default target locations

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#62]
set reformed target locations by default

All countries, except customized CB, and NG in the separate commit for proposal

**Comment by fakhrihawari** [comment]
Link: https://github.com/fakhrihawari/ngm-reportHub/tree/target-location-default

**Comment by fakhrihawari** [comment]
Do we push this?

**Comment by drfaustusfade** [comment]
that's alright

**Comment by fakhrihawari** [comment]
okay, link PR:
https://github.com/drfaustusfade/ngm-reportHub/pull/122
