### ISSUE TITLE
angularjs update

### ISSUE THREAD

**Issue by drfaustusfade** [drfaustusfade/ngm-reportDesk#9]
gradually update angular to the latest version

https://docs.angularjs.org/guide/migration

**Comment by drfaustusfade** [comment]
https://github.com/drfaustusfade/ngm-dashboard-framework/tree/v0.4.2
https://github.com/drfaustusfade/ngm-reportHub/tree/update-to-angularjs-1.8.2
note $http supports only then/catch, with response.data 
- [x] to check if all $http requests updated
- [x] to test if other breaking changes

updated DEV

**Comment by fakhrihawari** [comment]
a bug that I found after update :
1.
<img width="1218" alt="Screen Shot 2020-12-21 at 12 41 03" src="https://user-images.githubusercontent.com/12655589/102743453-12822900-438a-11eb-9e0d-da8b6cb3a93b.png">

after click the preview icon the error happen

**Comment by fakhrihawari** [comment]
Should we follow all the step to migrate from this
https://codecraft.tv/courses/angularjs-migration/

**Comment by drfaustusfade** [comment]
partially, the plan for now
1. es6 with babel and webpack following https://github.com/toddmotto/angularjs-styleguide (please check)
2. transition to typescript
3. prepare for other framework migration and to try dual booting

Note I have almost completed the setup of point 1, it works fine, I ll update when ready

**Comment by drfaustusfade** [comment]
updated angularjs 1.8.2 PROD and DEV https://github.com/drfaustusfade/ngm-reportHub/pull/43
